language: node_js
node_js:
  - 'v0.12.7'
  - 'v4'
install:
  # Install peerDependencies on > npm3
  # When all dependencies declare bitcore-lib as a peerDependency this can be bumped up, but this matches the current ecosystem version expected by dependencies
  - if [ $(npm --version | sed 's/\..*//g') -ge 3 ]; then npm install bitcore-lib@0.13.7; fi
  - npm install
